### ISSUE TITLE
Create icons for all common Sippy functions

### ISSUE THREAD

**Issue by Studio384** [optimise-group/valkyrie#6]
- Arrow icons
  - [x] `arrow-right-to-bracket`
  - [x] `arrow-right-from-bracket`
  - [x] arrows (4 icons: left, right, top, bottom)
  - [x] angles (4 icons: left, right, top, bottom)
  - [x] `download`
- Feature icons
  - [x] `home`
  - [x] `backstage`
  - [x] `dashboard`
  - [x] `devices` (as in accounts)
  - [x] `pbxes`/`domains`
  - [x] `pbx`/`domain`
  - [x] `reseller`
  - [x] `phonenumber`/`sim-card`
  - [x] `office-phone`
  - [x] `provider`
  - [x] `box-full` (as in onboarding)
  - [x] `integration`
  - [x] `logs`
  - [x] `calls`
  - [x] `queues`
  - [x] `flex-desk` (`user-clock`/`user-arrow-right-to-bracket`)
  - [x] `phonebook`
  - [x] `id`
  - [x] `files`
  - [x] `audio`
  - [x] `image`
  - [x] `video`
  - [x] `timetable`
  - [x] `calendar-holidays`
  - [x] `globe` (as in unrestricted number)
  - [x] `pin` (as in destination)
  - [x] `provisioning`
  - [x] `ivr`
  - [x] `voicemail`
  - [x] `custom-destinations`
- User icons
  - [x] `user`
  - [x] `user-account`
  - [x] `users`
- Others
  - [x] `stars` (as in recently used)
  - [x] `bug`
  - [x] `lightbulb`
- UI icons
  - [x] `spinner-third`
  - [x] `bars` (as in menu)
  - [x] `eye`
  - [x] `eye-slashed`
  - [x] `help`
  - [x] `feedback`
  - [x] `gear`
  - [x] `search`
  - [x] `plus`
  - [x] personalization
  - [x] `locked`
  - [x] `unlocked`
  - [x] `sun` (as in theme)
  - [x] `moon` (as in theme)
  - [x] `eclipse` (as in theme)
  - [x] `pie-chart`
  - [x] `send`
  - [x] `info`
  - [x] `book`
  - [x] `pin`
  - [x] `unpin`
  - [x] `x-mark`
  - [x] `clock`
  - [x] `euro`
  - [x] `email`
  - [x] `email-sales`
  - [x] `link`
  - [x] `unlink`
  - [x] `warning`
  - [x] `shield`
  - [x] `trunk`
  - [x] `calendar`
  - [x] `refresh`
  - [x] `call-incoming`
  - [x] `call-outgoing`
  - [x] `pencil`
  - [x] `trash`
  - [x] `play`
  - [x] `pause`
  - [x] `volume-none`, `volume-low`, `volume-medium`, `volume-high`
  - [x] `list-checkbox`
  - [x] `order`
  - [x] `phone`
  - [x] `blf`
  - [x] `sliders`
  - [x] `power`
  - [x] `refresh`
  - [x] `check-circle`
  - [x] `floppy-disk`
  - [x] `envelope`
- Brand icons
  - [x] `sippy`
  - [x] `edge`
  - [x] `firefox`
  - [x] `chrome`
  - [x] `safari`
